workspace = { members = ["orm_macro_derive"] }
[package]
name = "orm_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_orm_macro_derive = {path = "./orm_macro_derive/"}
